name: web3_ethereum
description: Binding Dart to window.ethereum JavaScript object
version: 0.0.1
homepage: https://github.com/inveker/web3_ethereum

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  js: ^0.6.4

dev_dependencies:
  flutter_lints: ^2.0.0